#!/bin/csh
#
# LSF batch script to run an MPI application
#
#SBATCH -A P19010000           # project code
#SBATCH -t 12:00:00               # wall-clock time (hrs:mins)
#SBATCH -n 1                   # number of tasks in job         
#SBATCH --ntasks-per-node=1     # run 16 MPI tasks per node
#SBATCH -J ne30_cmip_script_rename_ne30 # job name
#SBATCH -o myjob.%J.out        # output file name in which %J is replaced by the job ID
#SBATCH -p dav                 # queue

#run the executable
#source /glade/u/apps/opt/slurm_init/init.csh
module load ncl/6.4.0

ncl < rename_and_convert_cmip_hist.ncl

